-- ReaScript Name: Toggle bypass for the currently active Airwindows console type for the selected tracks
-- Version: 2.0
-- Author: jahudka
-- Links:
--   Documentation https://github.com/jahudka/reaper-consolefx
-- Changelog:
--   v2.0 (2020-12-21)
--    - extracted utility methods to *_utils.lua
--    - added support for Console 7 Cascade
--   v1.4 (2020-12-09)
--    - added support for Console 7
--   v1.2 (2020-02-16)
--    - toggle bypass for any console fx that aren't offline
--   v1.1 (2020-01-05)
--    - added all the Console types
--    - document the fact that you probably don't need to edit this script's configuration
--   v1.0 (2020-01-05)
--    - initial release
-- About:
--   This script can be used to toggle the bypass state of Airwindows Console plugins
--   inside the post-fader routing matrix generated by the `*_create_busses.lua` script.
--   See https://github.com/jahudka/reaper-consolefx#enabling--disabling-console-processing
--   for an usage overview.

-- HELPERS

package.path = (function ()
    local info = debug.getinfo(1, 'S')
    local s = package.config:sub(1, 1)
    return info.source:sub(2):gsub(s .. '[^' .. s .. ']+$', '') .. s .. '?.lua;' .. package.path
end)()

require('jahudka_consolefx_utils')

if not log then
    reaper.MB("This script depends on 'jahudka_consolefx_utils.lua' but it appears it isn't installed! Please install it first and then run this script again.", "Whoops!", 0)
end

local function find_current_console_type(track)
    local plugins = find_console_plugins(track)

    if #plugins < 1 then
        return nil
    end

    for _, plugin in ipairs(plugins) do
        if not plugin.offline then
            return plugin.type, plugin.enabled
        end
    end

    return nil
end

-- END HELPERS

function toggle_console_enabled()
    local tracks = get_target_tracks()

    if #tracks < 1 then
        return
    end

    local _, enabled = find_current_console_type(tracks[1])
    enabled = not enabled

    reaper.Undo_BeginBlock()

    for _, track in ipairs(tracks) do
        for _, plugin in ipairs(find_console_plugins(track)) do
            if plugin.offline ~= true and plugin.enabled ~= enabled then
                reaper.TrackFX_SetEnabled(track, plugin.index, enabled)
            end
        end
    end

    reaper.Undo_EndBlock('Toggle Airwindows Console enabled', -1)
end

toggle_console_enabled()
